/**
 * Password Generator Utility for Class Rep Authentication
 * 
 * Generates secure, random passwords for faculty-assigned reps.
 * These passwords cannot be reset via email - they can only be regenerated by faculty.
 */

/**
 * Generate a strong random password
 * Format: 3 words + 4 random digits + 1 special character
 * Example: Apple-Blue-Server-7492!
 * 
 * @returns {string} A secure random password
 */
export const generateSecurePassword = () => {
  // Simple word list for memorable passwords
  const words = [
    'Admin', 'Alert', 'Apple', 'Apply', 'Arrow', 'Atlas', 'Atom',
    'Badge', 'Beach', 'Board', 'Boost', 'Brain', 'Bridge', 'Bright',
    'Build', 'Cable', 'Cache', 'Cadet', 'Cedar', 'Chart', 'Chase',
    'Child', 'Class', 'Clean', 'Clear', 'Clock', 'Cloud', 'Coach',
    'Coast', 'Comet', 'Core', 'Crown', 'Curve', 'Cycle', 'Dance',
    'Denim', 'Dense', 'Desert', 'Dial', 'Diamond', 'Direct', 'Drive',
    'Eagle', 'Early', 'Easel', 'Eight', 'Elate', 'Ember', 'Empty',
    'Entry', 'Equal', 'Error', 'Event', 'Exact', 'Exist', 'Extra'
  ];

  const specialChars = ['!', '@', '#', '$', '%', '&', '*', '+'];

  // Select 3 random words
  const word1 = words[Math.floor(Math.random() * words.length)];
  const word2 = words[Math.floor(Math.random() * words.length)];
  const word3 = words[Math.floor(Math.random() * words.length)];

  // Generate 4 random digits
  const digits = Math.floor(Math.random() * 10000)
    .toString()
    .padStart(4, '0');

  // Select 1 random special character
  const special = specialChars[Math.floor(Math.random() * specialChars.length)];

  // Combine with hyphens
  return `${word1}-${word2}-${word3}-${digits}${special}`;
};

/**
 * Generate a temporary password for password reset links
 * Format: 32 character random hex string
 * 
 * @returns {string} A temporary reset token
 */
export const generateResetToken = () => {
  const chars = '0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ';
  let token = '';
  for (let i = 0; i < 32; i++) {
    token += chars.charAt(Math.floor(Math.random() * chars.length));
  }
  return token;
};

/**
 * Validate password strength
 * Requirements:
 * - Minimum 8 characters
 * - At least one uppercase letter
 * - At least one lowercase letter
 * - At least one number
 * - At least one special character
 * 
 * @param {string} password The password to validate
 * @returns {object} { isValid: boolean, errors: string[] }
 */
export const validatePasswordStrength = (password) => {
  const errors = [];

  if (!password || password.length < 8) {
    errors.push('Password must be at least 8 characters long');
  }

  if (!/[A-Z]/.test(password)) {
    errors.push('Password must contain at least one uppercase letter');
  }

  if (!/[a-z]/.test(password)) {
    errors.push('Password must contain at least one lowercase letter');
  }

  if (!/[0-9]/.test(password)) {
    errors.push('Password must contain at least one number');
  }

  if (!/[!@#$%&*+]/.test(password)) {
    errors.push('Password must contain at least one special character (!@#$%&*+)');
  }

  return {
    isValid: errors.length === 0,
    errors
  };
};
